### ISSUE TITLE
No Wire.beginTransmission() or Wire.endTransmission() needed for Wire.requestFrom().

### ISSUE THREAD

**Issue by Koepel** [adafruit/Adafruit_IS31FL3731#1]
The Wire.requestFrom() is encapsulated by Wire.beginTransmission() and Wire.endTransmission(). The beginTransmission and endTransmission are only for writing data, and should not be used with Wire.requestFrom().

**Comment by microbuilder** [comment]
Feel free to submit a tested pull request which we will be happy to integrate.

**Comment by Koepel** [comment]
I think that a tested pull request is not needed. It is not about communicating with the chip, it is the wrong use of the Wire library.

**Comment by Koepel** [comment]
Could you check the code ? 
I reported a bug, but now you closed this issue and you kept the bug in the code.

If you want to keep those bugs, you might as well close most of my open issues about the use of the Wire library.
The reason I do this, because on the Arduino forum I see those bugs when people ask questions about I2C devices. Since Adafruit is the front runner with hardware, tutorials and software, I wanted to help Adafruit for free to make better code.

I say it again: The Wire.requestFrom() should not be encapsulated by Wire.beginTransmission() and Wire.endTransmission.
