### ISSUE TITLE
Lack of license

### ISSUE THREAD

**Issue by MiLeG** [adafruit/Adafruit_IS31FL3731#15]
Greetings,
I would like to use this library in my project, but I am unsure about the terms of use since the code is unlicensed.

According to this [page](https://choosealicense.com/no-permission/#for-users), it's best to ask for the owner to license their code than to use unlicensed code. So, could you please add a license to your code? (preferably MIT 😄 )

Thank you for your time!

**Comment by ladyada** [comment]
@dherrada hey dylan, wanna add our standard license dox here?

**Comment by evaherrada** [comment]
@ladyada Sorry for the late response. I'll get right on it.

**Comment by ladyada** [comment]
all good thank you :)

**Comment by evaherrada** [comment]
I added the license and the code of conduct since it seemed like that was also missing
