### ISSUE TITLE
boolean Adafruit_IS31FL3731::begin(uint8_t addr) always returns true

### ISSUE THREAD

**Issue by anecdata** [adafruit/Adafruit_IS31FL3731#4]
The Adafruit Learn tutorial indicates that the method will return a boolean indicating whether the board is present / functioning:

> Then in your setup, call begin(address) to initialize the driver. Begin() will return false if the matrix was not found, and true if initialization worked out

[https://learn.adafruit.com/adafruit-15x7-7x15-charlieplex-led-matrix-charliewing-featherwing/library-reference](https://learn.adafruit.com/adafruit-15x7-7x15-charlieplex-led-matrix-charliewing-featherwing/library-reference)

However, it always returns true, so the calling sketch can't currently check for presence / function.

**Comment by ladyada** [comment]
fixed
